### ISSUE TITLE
MQTT & homeassistant

### ISSUE THREAD

**Issue by friendlyFriend4000** [se1exin/ESPBlinds#10]
I am sort of lost in terms on how to control my blinds motor. I have successfully setup a wifi connection between my esp8266 and MQTT connection also reports as successfull (at that's what the console reports). Now how do I actually operate the motor? I dont see esp8266 on my homeassistant dashboard.

**Comment by se1exin** [comment]
Hi there, if you've used the code from this repo to flash the ESP8266 you will need to manually add each MQTT topic to the Home Assistant config.

Here's my config for HA:
```
mqtt:
  sensor:
    - name: "Bedroom Blinds: Status"
      unique_id: "esp8266_blinds_01_status"
      object_id: "esp8266_blinds_01_status"
      state_topic: "home/esp8266_blinds_01/status"
    - name: "Bedroom Blinds: Current Mode"
      unique_id: "esp8266_blinds_01_mode"
      object_id: "esp8266_blinds_01_mode"
      state_topic: "home/esp8266_blinds_01/mode"
    - name: "Bedroom Blinds: Enabled"
      unique_id: "esp8266_blinds_01_enabled"
      object_id: "esp8266_blinds_01_enabled"
      state_topic: "home/esp8266_blinds_01/enabled"
    - name: "Bedroom Blinds: State"
      unique_id: "esp8266_blinds_01_state"
      object_id: "esp8266_blinds_01_state"
      state_topic: "home/esp8266_blinds_01/state"
    - name: "Bedroom Blinds: Current Steps"
      unique_id: "esp8266_blinds_01_steps"
      object_id: "esp8266_blinds_01_steps"
      state_topic: "home/esp8266_blinds_01/steps"
    - name: "Bedroom Blinds: Direction"
      unique_id: "esp8266_blinds_01_direction"
      object_id: "esp8266_blinds_01_direction"
      state_topic: "home/esp8266_blinds_01/direction"
    - name: "Bedroom Blinds: Vertical Steps"
      unique_id: "esp8266_blinds_01_steps_vertical"
      object_id: "esp8266_blinds_01_steps_vertical"
      state_topic: "home/esp8266_blinds_01/steps/vertical"
    - name: "Bedroom Blinds: Open Mode"
      unique_id: "esp8266_blinds_01_mode_open"
      object_id: "esp8266_blinds_01_mode_open"
      state_topic: "home/esp8266_blinds_01/mode/open"
    - name: "Bedroom Blinds: Close Mode"
      unique_id: "esp8266_blinds_01_mode_close"
      object_id: "esp8266_blinds_01_mode_close"
      state_topic: "home/esp8266_blinds_01/mode/close"
    - name: "Bedroom Blinds: Open Delay"
      unique_id: "esp8266_blinds_01_delay_open"
      object_id: "esp8266_blinds_01_delay_open"
      state_topic: "home/esp8266_blinds_01/delay/open"
    - name: "Bedroom Blinds: Close Delay"
      unique_id: "esp8266_blinds_01_delay_close"
      unique_id: "esp8266_blinds_01_delay_close"
      state_topic: "home/esp8266_blinds_01/delay/close"

  switch:
    - name: "Bedroom Blinds: Enabled"
      unique_id: "esp8266_blinds_01_enabled_switch"
      object_id: "esp8266_blinds_01_enabled_switch"
      state_topic: "home/esp8266_blinds_01/enabled"
      command_topic: "home/esp8266_blinds_01/control/enabled"
      availability_topic: "home/esp8266_blinds_01/status"
      payload_available: "connected"
      payload_not_available: "disconnected"
      qos: 1
      payload_on: 1
      payload_off: 0
    - name: "Bedroom Blinds: Opened"
      unique_id: "esp8266_blinds_01_open_switch"
      object_id: "esp8266_blinds_01_open_switch"
      state_topic: "home/esp8266_blinds_01/state"
      command_topic: "home/esp8266_blinds_01/control/blinds"
      availability_topic: "home/esp8266_blinds_01/status"
      payload_available: "connected"
      payload_not_available: "disconnected"
      qos: 1
      payload_on: "opened"
      payload_off: "closed"
```
